blank_issues_enabled: false
contact_links:
  - name: 💬 Ask Questions & General Discussions
    url: https://github.com/chayanforyou/QuickBall/discussions
    about: Please ask questions or start general discussions in GitHub Discussions.
